---
title: "Data prep script 2: Compute NIH Toolbox Flanker Score"
author: "Brent Rappaport"
date: "`r format(Sys.time(),  '%Y-%m-%d')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
subtitle: Template Rmd
editor_options:
  chunk_output_type: console
toc: yes
---

# About
This script computes the NIH Toolbox Flanker score

# 1. Get Setup
## 1.1. Clear everything & set width
```{r echo=TRUE, results='hide', message=FALSE}
    options(width=80, Ncpus = 6) #Set width
    rm(list=ls())     #Remove everything from environment
    cat("\014")       #Clear Console
```

## 1.2. Load Libraries
```{r echo=TRUE, results='hide', message=FALSE}
  # renv::restore()     #restore environment
  library(knitr)      #allows rmarkdown files
  library(haven)      #helps import stata
  library(questionr)  #allows lookfor function
  library(MASS)       #calculate residualized scores
  library(tidyverse)  #plotting/cleaning, etc.
  library(broom)      #nice statistical output
  library(here)       #nice file paths
  library(expss)      #labeling variables/values
  library(psych)      #used for statistical analyses
  library(workflowr)  #helps with workflow
```

## 1.3. Get the Working Directory
```{r}
  here()
```

## 1.4. Set seed
```{r}
     set.seed(312)    #Set seed
```

## 1.5 Load Data
```{r}
here::i_am("work/management/data02_LDDM_rdoc.Rmd")
LDDM_cleaning04_fullbeh_rdoc <- read.csv(here("./RDoC/DDM_Trialwise_Prepped/Block-Based/RDoC_ERN_HDDM_data_acc_coded_rev_B11.csv"))
```

## 3.1 All trials
```{r}
# Setup the dataset with the needed variables (eg., ID, block # 1-11, trial # 1-30 per block)
LDDM_cleaning04_rdoc_calc1 <- LDDM_cleaning04_fullbeh_rdoc %>%
  group_by(subj_idx) %>%
  mutate(block = c(rep(1,30),rep(2,30),rep(3,30),rep(4,30),rep(5,30),rep(6,30),rep(7,30),rep(8,30),rep(9,30),rep(10,30),rep(11,30))) %>%
  group_by(subj_idx, block) %>%
  mutate(trial = 1:30) %>%
  filter(rt<900)

# Calculate the accuracy per subject (according to NIH toolbox this should be the number of correct responses * 5/total trials (330))
LDDM_cleaning04_rdoc_calc2 <- LDDM_cleaning04_rdoc_calc1 %>%
  group_by(subj_idx) %>%
  reframe(accuracy_score = sum(response==1)*(5/length(trial)))

LDDM_cleaning04_rdoc_ind <-  LDDM_cleaning04_rdoc_calc1 %>%
  group_by(subj_idx) %>% # per subject
  filter(stim=="incongruent" & response==1) %>% #incongruent trials with correct response
  mutate(mean_rt = mean(rt),
         sd_rt = sd(rt)) %>% # compute individual mean and sd RT
  filter(rt>=0.1 & rt>(mean_rt - 3*sd_rt) & rt<(mean_rt + 3*sd_rt)) %>% #remove trials less than 100ms and less than 3SD below or 2SD above the mean RT
  reframe(med_rt = median(rt)*1000) %>% # compute individual level median RT
  mutate(rt_score = 5-(5*((log(med_rt)-log(250))/(log(1000)-log(250)))),
         rt_score_truncated = 5-(5*((log(med_rt)-log(500))/(log(3000)-log(500)))))

# RT of correct responses, and interference effect difference score (RT of incongruent - congruent)
LDDM_cleaning04_rdoc_ind_rt <-  LDDM_cleaning04_rdoc_calc1 %>%
  group_by(subj_idx) %>%
  mutate(rt_correct = ifelse(response==1, median(rt, na.rm=TRUE), NA)) %>%
    pivot_wider(names_from=stim, id_cols=c(subj_idx, response, block, trial, rt_correct), values_from=rt, names_prefix="rt_") %>%
    group_by(subj_idx) %>%
    mutate(mean_rt_incongruent_log = mean(log(rt_incongruent), na.rm=TRUE),
           mean_rt_congruent_log = mean(log(rt_congruent), na.rm=TRUE),
           
         sd_rt_incongruent_log = sd(log(rt_incongruent), na.rm=TRUE),
         sd_rt_congruent_log = sd(log(rt_congruent), na.rm=TRUE)) %>%
#remove trials less than 150ms, less than 3SD below, or 3SD above the mean log RT per Dillon et al, 2015
  filter(rt_incongruent>=0.15 | rt_congruent>=0.15) %>%
  filter(log(rt_incongruent)<(mean_rt_incongruent_log + 3*sd_rt_incongruent_log) |
         log(rt_congruent)>(mean_rt_congruent_log - 3*sd_rt_congruent_log)) %>%
  
    reframe(rt_correct = median(log(rt_correct), na.rm=TRUE),
            rt_interference = median(log(rt_incongruent), na.rm=TRUE)-median(log(rt_congruent), na.rm=TRUE)) %>%
  mutate(ID=subj_idx) %>%
  select(-subj_idx)

LDDM_cleaning04_rdoc_calc3 <- LDDM_cleaning04_rdoc_calc1 %>%
  full_join(LDDM_cleaning04_rdoc_ind, by = 'subj_idx') %>%
  full_join(LDDM_cleaning04_rdoc_calc2, by='subj_idx') %>%
  group_by(subj_idx) %>% # per subject
  mutate(total_accuracy_perc = sum(response==1)/length(response)) %>% # compute total accuracy percentage
  reframe(flanker_score_list_rdoc = if_else(total_accuracy_perc>0.8, accuracy_score+rt_score, accuracy_score),
            flanker_score_list_rdoc_truncated = if_else(total_accuracy_perc>0.8, accuracy_score+rt_score_truncated, accuracy_score),
            accuracy = mean(total_accuracy_perc)) %>%# if accuracy is above 80% then add accuracy and rt flanker scores, if not base the flanker score only on accuracy
  transmute(ID=subj_idx, flanker_score_list_rdoc=flanker_score_list_rdoc, flanker_score_list_rdoc_truncated=flanker_score_list_rdoc_truncated, accuracy=accuracy) %>%
  group_by(ID) %>% # per subject
  reframe(flanker_score_rdoc = mean(flanker_score_list_rdoc),
            flanker_score_rdoc_truncated = mean(flanker_score_list_rdoc_truncated),
            accuracy = mean(accuracy))

LDDM_cleaning04_rdoc_accuracy_by_condition <- LDDM_cleaning04_rdoc_calc1 %>%
  full_join(LDDM_cleaning04_rdoc_ind, by = 'subj_idx') %>%
  full_join(LDDM_cleaning04_rdoc_calc2, by='subj_idx') %>%
  group_by(subj_idx, stim) %>% # per subject
  mutate(total_accuracy_perc = sum(response==1)/length(response)) %>% # compute total accuracy percentage
  reframe(accuracy_by_stim = mean(total_accuracy_perc)) %>%
  pivot_wider(names_from=stim, values_from=c(accuracy_by_stim), id_cols=c(subj_idx), names_prefix="accuracy_") %>%
  mutate(ID=subj_idx,
         accuracy_congruent_log = log(accuracy_congruent))

LDDM_cleaning04_rdoc_calc4 <- LDDM_cleaning04_rdoc_calc3 %>%
  full_join(LDDM_cleaning04_rdoc_accuracy_by_condition, by="ID") %>%
  select(-subj_idx) %>%
  full_join(LDDM_cleaning04_rdoc_ind_rt, by="ID")
```

### Only 20 trials
```{r}
# Setup the dataset with the needed variables (eg., ID, block # 1-11, trial # 1-30 per block)
LDDM_cleaning04_rdoc_calc1_short_incon <- LDDM_cleaning04_rdoc_calc1 %>%
  group_by(subj_idx) %>%
  filter(stim=="incongruent") %>%
  slice_head(n=8)

LDDM_cleaning04_rdoc_calc1_short_con <- LDDM_cleaning04_rdoc_calc1 %>%
  group_by(subj_idx) %>%
  filter(stim=="congruent") %>%
  slice_head(n=12)

LDDM_cleaning04_rdoc_calc1_short <- rbind(LDDM_cleaning04_rdoc_calc1_short_incon, LDDM_cleaning04_rdoc_calc1_short_con) %>%
  arrange(subj_idx)

# Calculate the accuracy per subject (according to NIH toolbox this should be the number of correct responses * 5/total trials (330))
LDDM_cleaning04_rdoc_calc2_short <- LDDM_cleaning04_rdoc_calc1_short %>%
  group_by(subj_idx) %>%
  reframe(accuracy_score = sum(response==1)*(5/length(trial)))

LDDM_cleaning04_rdoc_ind_short <-  LDDM_cleaning04_rdoc_calc1_short %>%
  group_by(subj_idx) %>% # per subject
  filter(stim=="incongruent" & response==1) %>% #incongruent trials with correct response
  mutate(mean_rt = mean(rt),
         sd_rt = sd(rt)) %>% # compute individual mean and sd RT
  filter(rt>=0.1 & rt>(mean_rt - 3*sd_rt) & rt<(mean_rt + 3*sd_rt)) %>% #remove trials less than 100ms and less than 3SD below or 2SD above the mean RT
  reframe(med_rt = median(rt)*1000) %>% # compute individual level median RT
  mutate(rt_score = 5-(5*((log(med_rt)-log(250))/(log(1000)-log(250)))),
         rt_score_truncated = 5-(5*((log(med_rt)-log(500))/(log(3000)-log(500)))))

LDDM_cleaning04_rdoc_calc3_short <- LDDM_cleaning04_rdoc_calc1_short %>%
  full_join(LDDM_cleaning04_rdoc_ind, by = 'subj_idx') %>%
  full_join(LDDM_cleaning04_rdoc_calc2, by='subj_idx') %>%
  group_by(subj_idx) %>% # per subject
  mutate(total_accuracy_perc = sum(response==1)/length(response)) %>% # compute total accuracy percentage
  reframe(flanker_score_list_rdoc = if_else(total_accuracy_perc>0.8, accuracy_score+rt_score, accuracy_score),
            flanker_score_list_rdoc_truncated = if_else(total_accuracy_perc>0.8, accuracy_score+rt_score_truncated, accuracy_score),
            accuracy = mean(total_accuracy_perc)) %>%# if accuracy is above 80% then add accuracy and rt flanker scores, if not base the flanker score only on accuracy
  transmute(ID=subj_idx, flanker_score_list_rdoc=flanker_score_list_rdoc, flanker_score_list_rdoc_truncated=flanker_score_list_rdoc_truncated, accuracy=accuracy) %>%
  group_by(ID) %>% # per subject
  reframe(flanker_score_rdoc = mean(flanker_score_list_rdoc),
            flanker_score_rdoc_truncated = mean(flanker_score_list_rdoc_truncated),
            accuracy = mean(accuracy))
```

# 4. Closing out
  In this step, go ahead and close out of the file and quit R without saving  
  the work space.
```{r}
save(LDDM_cleaning04_fullbeh_rdoc, file=here("./work/data/LDDM_cleaning04_fullbeh_rdoc.RData"))

save(LDDM_cleaning04_rdoc_calc4, LDDM_cleaning04_rdoc_calc1, LDDM_cleaning04_rdoc_calc3_short, LDDM_cleaning04_rdoc_ind_short, file=here("./work/data/LDDM_cleaning04_rdoc_calc4.RData"))
   # renv::snapshot()   #Take a snapshot of environment
```

